spring:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/test}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: "${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}"
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



